### ISSUE TITLE
Handle tarfile permission errors

### ISSUE THREAD

**Issue by srid** [ActiveState/applib#11]
Yet another instance of tarfile unreliability:

```
airi-0.0.1> building ...
error: unhandled exception caught - shown below
error: [Errno 13] Permission denied: '.\\airi-0.0.1\\AIRi'
Traceback (most recent call last):
  File "F:\as\pypm\pypm\builder\mason.py", line 111, in build_package
    d, _ = sh.unpack_archive(location)
  File "F:\as\pypm\pypm\external\applib\sh.py", line 37, in unpack_archive
    return (implementor(filename).extract(), filetype)
  File "F:\as\pypm\pypm\external\applib\_compression.py", line 112, in extract
    f, f.getnames())
  File "F:\as\pypm\pypm\external\applib\_compression.py", line 48, in extractall
_with_single_toplevel
    f.extractall()
  File "C:\Python27\Lib\tarfile.py", line 2046, in extractall
    self.extract(tarinfo, path)
  File "C:\Python27\Lib\tarfile.py", line 2083, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "C:\Python27\Lib\tarfile.py", line 2159, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "C:\Python27\Lib\tarfile.py", line 2198, in makefile
    target = bltn_open(targetpath, "wb")
IOError: [Errno 13] Permission denied: '.\\airi-0.0.1\\AIRi'
```

**Comment by srid** [comment]
Related, but different, error on OSX:

```
Traceback (most recent call last):
 File "/Users/apy/as/pypm/pypm/builder/mason.py", line 111, in build_package
   d, _ = sh.unpack_archive(location)
 File "/Users/apy/as/pypm/pypm/external/applib/sh.py", line 37, in unpack_archive
   return (implementor(filename).extract(), filetype)
 File "/Users/apy/as/pypm/pypm/external/applib/_compression.py", line 112, in extract
   f, f.getnames())
 File "/Users/apy/as/pypm/pypm/external/applib/_compression.py", line 48, in extractall_with_single_toplevel
   f.extractall()
 File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 2046, in extractall
   self.extract(tarinfo, path)
 File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 2083, in extract
   self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
 File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 2159, in _extract_member
   self.makefile(tarinfo, targetpath)
 File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 2198, in makefile
   target = bltn_open(targetpath, "wb")
IOError: [Errno 21] Is a directory: './airi-0.0.1/AIRi'
```
